Algoritmo "exercicio 6 pag 22"
//  
//  
// 
//  
// Descrição   : calcule e mostre a diferença do produto de A e B pelo produto de C e D
// Autor(a)    : Pedro
// Data atual  : 25/02/2021
Var
// Seção de Declarações das variáveis 
a,b,c,d,produto: real


Inicio
 escreva("A: ")
 leia (a)
 escreva ("B: ")
 leia (b)
 escreva ("C: ")
 leia (c)
 escreva ("D: ")
 leia (d)
 produto:=a*b-c*d
 escreva ("produto final: ",produto)


Fimalgoritmo