Algoritmo "exercicio 17 pag 23"
//
//
// Descrição   :  calcule quanto tempo leva para o carro mais veloz tomar essa distância do outro carro.
// Autor(a)    : Pedro
// Data atual  : 06/03/2021
Var
  carrox,carroy,temp,dista: real
Inicio


 carrox := 60
 carroy := 90
 escreval ("qual a distância percorrida (em Km)?")
 leia (dista)
 temp := (carrox*dista)/30
 escreval ("o tempo sera: ",temp, " minutos.")


Fimalgoritmo