Algoritmo "EXER 5 PAG 22"
//  
//  
// 
//  
// Descrição   : CALCULAR MÉDIA
// Autor(a)    : Pedro
// Data atual  : 25/02/2021
Var
// Seção de Declarações das variáveis 
a,b,c, media : real


Inicio
 escreva ("Escreva a primeira nota: ")
 leia (a)
 escreva ("Escreva a segunda nota: ")
 leia (b)
 escreva ("Escreva a terceira nota: ")
 leia (c)
 media:= ((a*2)+(b*3)+(c*5))/10
 escreva ("A média do aluno é: ",media)

Fimalgoritmo