Algoritmo "exercicio 15 pag 23"
//  
//  
// 
//  
// Descrição   : determinar o consumo médio de um automóvel
// Autor(a)    : pedro
// Data atual  : 06/03/2021
Var
 distancia, combustivel, consumo : real


Inicio
 escreval ("Qual a distância total percorrida?(Em km)")
 leia (distancia)
 escreval ("Qual o total de combustivel gasto?(Em litros)")
 leia (combustivel)
 consumo := distancia/combustivel
 escreva ("O consumo médio é: ",consumo)
 escreva (" Km/l")


Fimalgoritmo