Algoritmo "Exerc4 Lista3"
//
// Professor: Roberto Tambasco
// Descrição   : Calcule e mostre a soma dos números impares entre 1 e 100, inclusive
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2021
Var
a, soma : inteiro


Inicio

para a de 1 ate 100 faca
 se (a mod 2 = 1) entao
 escreval("+",a)
 soma <- soma+a
 fimse
fimpara
escreval("soma dos números impares de 1 a 100: ",soma)
Fimalgoritmo