Algoritmo "exerc1 lista2"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2021
Var
 a, b, c, d : real


Inicio
escreval ("informe A: ")
leia (a)
escreval ("informe B: ")
leia (b)
escreval ("informe C: ")
leia (c)
escreval ("informe D: ")
leia (d)

se (b>c) e (d>a) e (c+d>a+b) e (c>0) e (d>0) e (a%2=0) então

escreval ("valores aceitos")

senao

escreval("valores não aceitos")

fimse


Fimalgoritmo
